# Generated by Django 2.0.2 on 2018-05-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180509_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
