# Generated by Django 2.0.2 on 2018-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180519_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_for_you',
            field=models.BooleanField(default=True),
        ),
    ]
